/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import static javaapplication2.Logindb.ID;
import static javaapplication2.Logindb.client;
import static javaapplication2.Admindb.ID2;

/**
 *
 * @author User
 */
public class Clientdb extends javax.swing.JFrame {
    public  static String path ="";

    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    Statement smt=null;
    PreparedStatement statement=null; 
    PreparedStatement stmt=null;
    
    public Clientdb() {
        initComponents();
        
        
            ID_db.setEditable(false);
            ID_db.setText(ID);
            CF_db.setEditable(false);
            firstname_db.setEditable(false);
            fathersname_db.setEditable(false);
            lastname_db.setEditable(false);
            birthday_db.setEditable(false);
            birthstate_db.setEditable(false);
            jComboBox1.setEditable(false);
            jComboBox2.setEditable(false);
            address_db.setEditable(false);
            email_db.setEditable(false);
            phonenumber_db.setEditable(false);
            pa.setEnabled(false);
            jComboBox3.setEditable(false);
            jComboBox3.setVisible(false);
            
            jLabel14.setVisible(false);
            jLabel15.setVisible(false);
            username_db.setVisible(false);
            username_db.setEditable(false);
            password_db.setVisible(false);
            password_db.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CF_db = new javax.swing.JTextField();
        firstname_db = new javax.swing.JTextField();
        fathersname_db = new javax.swing.JTextField();
        lastname_db = new javax.swing.JTextField();
        birthday_db = new javax.swing.JTextField();
        birthstate_db = new javax.swing.JTextField();
        address_db = new javax.swing.JTextField();
        email_db = new javax.swing.JTextField();
        phonenumber_db = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ID_db = new javax.swing.JTextField();
        pa = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        username_db = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        password_db = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CF");

        jLabel2.setText("First Name");

        jLabel3.setText("Father's Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Birthday");

        jLabel6.setText("Birth State");

        jLabel7.setText("Gender");

        jLabel8.setText("Addres");

        jLabel9.setText("E-mail");

        jLabel10.setText("Phone Number");

        jLabel11.setText("Marital Status");

        jLabel12.setText("Photo");

        birthstate_db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthstate_dbActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "Female", "Male" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Attach");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Married", "Single", "Divorced", "Widow" }));

        jButton2.setText("Display Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Save");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setText("ID");

        ID_db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_dbActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "Client", "New Client" }));

        jLabel14.setText("Username");

        jLabel15.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(birthday_db)
                            .addComponent(lastname_db)
                            .addComponent(fathersname_db)
                            .addComponent(firstname_db)
                            .addComponent(birthstate_db, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(CF_db)
                            .addComponent(ID_db))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(56, 56, 56)
                                        .addComponent(email_db))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(address_db))
                                        .addGap(0, 44, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(username_db, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                                    .addComponent(password_db))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(phonenumber_db, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(ID_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CF_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(firstname_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fathersname_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lastname_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(birthday_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(birthstate_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(address_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(email_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(phonenumber_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jButton1)
                            .addComponent(pa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(username_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(password_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JFileChooser chooser =new JFileChooser(); 
     chooser.showOpenDialog(null);
     File f =chooser.getSelectedFile();
     String filename=f.getPath();
     Path source= FileSystems.getDefault().getPath(filename);
     Path d= source.getFileName();
     String filename1= f.getName();
     //System.out.println(path);
     
     Path target_dir = Paths.get("images", d.toString()).toAbsolutePath(); // todo [ath not working
     System.out.println(target_dir);
     
     try {
            Files.move(source, target_dir, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            System.err.println(e);
        }
     pa.setText(filename1);
     
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void birthstate_dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthstate_dbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthstate_dbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        rs=null;
        
        try{
            String sql="Select * from db_client;";
            conn = Conndb.getConnection(); 
            statement=(PreparedStatement) 
            conn.prepareStatement(sql);
            smt=conn.createStatement();
            rs=smt.executeQuery(sql);
            String ID1 = ID;
            
            while(rs.next())
            { 
               
             
            if(ID1.equals(rs.getString(1)))  
            {
            ID_db.setText(rs.getString(1));
            CF_db.setText(rs.getString(13));
            firstname_db.setText(rs.getString(2));
            fathersname_db.setText(rs.getString(3));
            lastname_db.setText(rs.getString(4));
            birthday_db.setText(rs.getString(5));
            birthstate_db.setText(rs.getString(6));
            jComboBox1.setSelectedItem(rs.getString(7));
            jComboBox2.setSelectedItem(rs.getString(8));
            address_db.setText(rs.getString(10));
            email_db.setText(rs.getString(11));
            phonenumber_db.setText(rs.getString(9));
            pa.setText(rs.getString(12));
            
            } 
        }
        }
       
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Enter Correct Data ", "Acces Denied",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            ID_db.setEditable(false);
            CF_db.setEditable(true);
            firstname_db.setEditable(true);
            fathersname_db.setEditable(true);
            lastname_db.setEditable(true);
            birthday_db.setEditable(true);
            birthstate_db.setEditable(true);
            jComboBox1.setEditable(true);
            jComboBox2.setEditable(true);
            address_db.setEditable(true);
            email_db.setEditable(true);
            phonenumber_db.setEditable(true);
            pa.setEnabled(true);
            jComboBox3.setEditable(true);
            jComboBox3.setVisible(true);
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            username_db.setVisible(true);
            username_db.setEditable(true);
            password_db.setVisible(true);
            password_db.setEditable(true);
            if (jComboBox3.getSelectedItem().equals("New Client")){
                ID_db.setText("");
                CF_db.setText("");
                firstname_db.setText("");
                fathersname_db.setText("");
                lastname_db.setText("");
                birthday_db.setText("");
                birthstate_db.setText("");
                jComboBox1.setSelectedItem("select");
                jComboBox2.setSelectedItem("select");
                address_db.setText("");
                email_db.setText("");
                phonenumber_db.setText("");
                pa.setText("");
                jLabel14.setText("");
                jLabel15.setText("");
                username_db.setText("");
                password_db.setText("");
                
            }
            
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        PreparedStatement statement=null;
        PreparedStatement stmt=null;
        ResultSet resultSet=null;
        
        
        if (jComboBox3.getSelectedItem().equals("Client")){
        try{
            conn = Conndb.getConnection();
            statement=(PreparedStatement)
            conn.prepareStatement("Update db_client SET ID=?,FirstName=?,FatherName=?,LastName=?,BirthDate=?,BirthPlace=?,Gender=?,MaritalStatus=?,PhoneNumber=?,Address=?,Email=?,Photo=?,CF=? Where ID='" + ID_db.getText() + "'");
            statement.setString(1,ID_db.getText());
            statement.setString(2,firstname_db.getText());
            statement.setString(3,fathersname_db.getText());
            statement.setString(4,lastname_db.getText());
            statement.setString(5,birthday_db.getText());
            statement.setString(6,birthstate_db.getText());
            statement.setObject(7,jComboBox1.getSelectedItem());
            statement.setObject(8,jComboBox2.getSelectedItem());
            statement.setString(10,address_db.getText());
            statement.setString(11,email_db.getText());
            statement.setString(9,phonenumber_db.getText());
            statement.setString(12,pa.getText());
            statement.setString(13,CF_db.getText());
            statement.executeUpdate();
            statement.close();
            conn.close();
            JOptionPane.showMessageDialog(null,"Data Updated Successfully", "Data Updated", JOptionPane.INFORMATION_MESSAGE);
            
            ID_db.setEditable(false);
            CF_db.setEditable(false);
            firstname_db.setEditable(false);
            fathersname_db.setEditable(false);
            lastname_db.setEditable(false);
            birthday_db.setEditable(false);
            birthstate_db.setEditable(false);
            jComboBox1.setEditable(false);
            jComboBox2.setEditable(false);
            address_db.setEditable(false);
            email_db.setEditable(false);
            phonenumber_db.setEditable(false);
            pa.setEnabled(true);
            jLabel14.setVisible(false);
            jLabel15.setVisible(false);
            username_db.setVisible(false);
            username_db.setEditable(false);
            password_db.setVisible(false);
            password_db.setEditable(false);
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error:" + e);
            }
            }
             
                else   if (jComboBox3.getSelectedItem().equals("New Client")){
                    ID_db.setText(null);
              try{
            conn = Conndb.getConnection();
            statement=(PreparedStatement)
            conn.prepareStatement("Insert db_client SET ID=?,FirstName=?,FatherName=?,LastName=?,BirthDate=?,BirthPlace=?,Gender=?,MaritalStatus=?,PhoneNumber=?,Address=?,Email=?,Photo=?,CF=?,Username=?,Password=?,admin=?");
            
            statement.setString(1,null);
            statement.setString(2,firstname_db.getText());
            statement.setString(3,fathersname_db.getText());
            statement.setString(4,lastname_db.getText());
            statement.setString(5,birthday_db.getText());
            statement.setString(6,birthstate_db.getText());
            statement.setObject(7,jComboBox1.getSelectedItem());
            statement.setObject(8,jComboBox2.getSelectedItem());
            statement.setString(10,address_db.getText());
            statement.setString(11,email_db.getText());
            statement.setString(9,phonenumber_db.getText());
            statement.setString(12,pa.getText());
            statement.setString(13,CF_db.getText());
            statement.setString(14,username_db.getText());
            statement.setString(15,password_db.getText());
            statement.setString(16,client);
            
            statement.executeUpdate();
            statement.close();
            conn.close();
            JOptionPane.showMessageDialog(null,"Data Updated Successfully", "Data Updated", JOptionPane.INFORMATION_MESSAGE);
            
            ID_db.setEditable(false);
            CF_db.setEditable(false);
            firstname_db.setEditable(false);
            fathersname_db.setEditable(false);
            lastname_db.setEditable(false);
            birthday_db.setEditable(false);
            birthstate_db.setEditable(false);
            jComboBox1.setEditable(false);
            jComboBox2.setEditable(false);
            address_db.setEditable(false);
            email_db.setEditable(false);
            phonenumber_db.setEditable(false);
            pa.setEnabled(true);
            jLabel14.setVisible(false);
            jLabel15.setVisible(false);
            username_db.setVisible(false);
            username_db.setEditable(false);
            password_db.setVisible(false);
            password_db.setEditable(false);
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error:" + e);
            }
                 
            
                
               
        }
        else {
                JOptionPane.showMessageDialog(null,"There are still some data unfilled", "Data Not Updated", JOptionPane.INFORMATION_MESSAGE);
                }
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ID_dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_dbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_dbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientdb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CF_db;
    private javax.swing.JTextField ID_db;
    private javax.swing.JTextField address_db;
    private javax.swing.JTextField birthday_db;
    private javax.swing.JTextField birthstate_db;
    private javax.swing.JTextField email_db;
    private javax.swing.JTextField fathersname_db;
    private javax.swing.JTextField firstname_db;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastname_db;
    private javax.swing.JLabel pa;
    private javax.swing.JTextField password_db;
    private javax.swing.JTextField phonenumber_db;
    private javax.swing.JTextField username_db;
    // End of variables declaration//GEN-END:variables
}
